apiVersion: v1
kind: Service
metadata:
  name: manju-nginx-clusterip-svc
  labels:
    app: nginx
    owner:manju
spec:
  type: ClusterIP
  selector:
    app: nginx 
  ports:
    - name: http
      port: 80     #  Serive port 
      targetPort: 80 #nginx listening on 80
