apiVersion: apps/v1
kind: Deployment
metadata:
  name: iammanjubhandari-backend-deploy
  labels:
    project: manjus-lab
    owner: manju
    env: dev
spec:
  replicas: 3 # running 3 pods for demo
  selector:
    matchLabels:
      app: iammanjubhandari-backend
  template:
    metadata:
      labels:
        app: iammanjubhandari-backend 
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          args:
            - "/bin/sh"
            - "-c"
            - "echo 'Hello - This is manju's nginx backend' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
# Node Port Service - expose Deployment outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: iammanjubhandari-backend-svc
  labels:
    project: manjus-lab
    owner: manju
    env: dev
spec:
  type: NodePort 
  selector:
    app: iammanjubhandari-backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
